server:
  port: 10100

spring:
  application:
    name: cloud-gateway
  cloud:
#    zookeeper:
#      connect-string: cloud.zook.com:2181
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: first_gateway
        uri: lb://provider-payment
        predicates:
        - Path=/get/**
        filters:
#        filter 名称必须是 RequestRateLimiter
        - name: RequestRateLimiter
          args:
#           令牌桶每秒填充平均速率
            redis-rate-limiter.replenishRate: 1
#           令牌桶的容量，允许在一秒钟内完成的最大请求数
            redis-rate-limiter.burstCapacity: 3
#           用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
            key-resolver: "#{@hostKeyResolver}"
#  redis:
#    cluster:
#      max-redirects: 3
#      nodes: cloud.redis.com:8002,cloud.redis.com:8003,cloud.redis.com:8801,cloud.redis.com:8802,cloud.redis.com:8803
#    client-name: redis-limit-cluster

#        - Method=post
#        - Cookie=aa, bb
#      - id: secod_gateway
#        uri: lb://provider-payment
#        predicates:
#        - Path=/get/**
#        - Query=aa, bb*
#        - After=2020-06-02T23:07:05.229+08:00[Asia/Shanghai]
#          Before=2020-06-02T23:03:05.229+08:00[Asia/Shanghai]

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
##    访问路径可以用显示IP地址
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://cloud.eureka.com:5050/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'