server:
  port: 20001
spring:
  application:
    name: provider-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:16666
        port: 8720

management:
  endpoints:
    web:
      exposure:
        include: '*'


