server:
  port: 9101

spring:
  application:
    name: consumer-payment-hystrix
#    zookeeper 注册发现
  cloud:
    zookeeper:
      connect-string: cloud.zook.com:2181

  #响应json 中 null值过滤
  jackson:
    default-property-inclusion: non_null

#eureka 配置
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://cloud.eureka.com:5050/eureka/

ribbon:
#读取服务端资源超时时间
  ReadTimeout: 1000
#与服务端建立连接超时时间
  ConnectTimeout: 1000
logging:
  level:
#    feign 日志，以什么级别监控哪个接口
    com.tfd.cloud.study.provider.feign.client.ProviderClient: debug
#    在feign client 中开启hystrix功能
feign:
  hystrix:
    enabled: true